version: '3.8'

services:

        postgresql-oddsmath-db:
                container_name: postgresql-oddsmath-db
                image: postgres:14
                ports:
                - "5432:5432"
                networks:
                        backend:
                                aliases:
                                - "postgresql-oddsmath-db"
                environment:
                        POSTGRES_PASSWORD: 123456
                        POSTGRES_USER: admin
                        POSTGRES_DB: oddsmathdb
                volumes:
                - postgresql-oddsmath-db-vol:/var/lib/postgresql/data

        oddsmath-fetcher-backend:
                container_name: oddsmath-fetcher-backend
                depends_on:
                        -       postgresql-oddsmath-db
                build:
                        dockerfile: Dockerfile
                        context: .
                ports:
                        -       "8080:8080"
                environment:
                        - DATABASE_URL=jdbc:postgresql://postgresql-oddsmath-db:5432/oddsmathdb
                        - DATABASE_USERNAME=admin
                        - DATABASE_PASSWORD=123456
                networks:
                        - backend

networks:
        backend:
                driver: bridge

volumes:
        postgresql-oddsmath-db-vol: