feign:
    autoconfiguration:
        jackson:
            enabled: true

spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/oddsmathdb}
        username: ${DATABASE_USERNAME:admin}
        password: ${DATABASE_PASSWORD:123456}
    jpa:
        properties:
            hibernate:
                jdbc:
                    batch_size: 10
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
